Pressenter\AgendaBundle\Entity\Category:
  type: entity
  table: categories
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
    color:
      type: string
      length: 255
      